version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SEAT_HOLD_DURATION_SECONDS=${SEAT_HOLD_DURATION_SECONDS:-60}
      - MAX_HOLDS_PER_USER=${MAX_HOLDS_PER_USER:-5}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 